"use client";

import { useState, useCallback, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Sparkles } from "lucide-react";
import { CreditIndicator } from "@/components/generate/credit-indicator";
import { ImagePreviewCard } from "@/components/generate/image-preview-card";
import { ProcessingOverlay } from "@/components/generate/processing-overlay";
import { ResultDisplay } from "@/components/generate/result-display";
import {
  SubjectTypeSelector,
  type SubjectType,
} from "@/components/generate/subject-type-selector";
import { UploadZone } from "@/components/generate/upload-zone";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useSession } from "@/lib/auth-client";

type GenerateStep = "upload" | "configure" | "processing" | "result";

// Mock user credits (in real app, fetch from API)
const MOCK_USER_CREDITS = 5;

// Mock plushie result image (in real app, generated by AI)
const MOCK_PLUSHIE_URL = "https://placehold.co/800x800/FFB6C1/FFF?text=Plushie+Result";

export default function GeneratePage() {
  const router = useRouter();
  const { data: session, isPending: isSessionPending } = useSession();

  const [step, setStep] = useState<GenerateStep>("upload");
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [subjectType, setSubjectType] = useState<SubjectType>("person");
  const [userCredits] = useState(MOCK_USER_CREDITS);

  // Redirect to login if not authenticated
  useEffect(() => {
    if (!isSessionPending && !session) {
      router.push("/login?callbackURL=/generate");
    }
  }, [session, isSessionPending, router]);

  // Clean up preview URL on unmount
  useEffect(() => {
    return () => {
      if (previewUrl) {
        URL.revokeObjectURL(previewUrl);
      }
    };
  }, [previewUrl]);

  const handleFileSelect = useCallback((file: File) => {
    setSelectedFile(file);
    const url = URL.createObjectURL(file);
    setPreviewUrl(url);
    setStep("configure");
  }, []);

  const handleRemoveFile = useCallback(() => {
    if (previewUrl) {
      URL.revokeObjectURL(previewUrl);
    }
    setSelectedFile(null);
    setPreviewUrl(null);
    setStep("upload");
  }, [previewUrl]);

  const handleReplaceFile = useCallback(() => {
    // Trigger file input click
    const input = document.createElement("input");
    input.type = "file";
    input.accept = "image/jpeg,image/png,image/webp";
    input.onchange = (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (file) {
        if (previewUrl) {
          URL.revokeObjectURL(previewUrl);
        }
        setSelectedFile(file);
        const url = URL.createObjectURL(file);
        setPreviewUrl(url);
      }
    };
    input.click();
  }, [previewUrl]);

  const handleGenerate = useCallback(() => {
    if (!selectedFile || userCredits < 1) return;
    setStep("processing");
  }, [selectedFile, userCredits]);

  const handleProcessingComplete = useCallback(() => {
    setStep("result");
  }, []);

  const handleCreateAnother = useCallback(() => {
    handleRemoveFile();
    setSubjectType("person");
    setStep("upload");
  }, [handleRemoveFile]);

  // Loading state while checking session
  if (isSessionPending) {
    return (
      <main id="main-content" className="container mx-auto px-4 py-8">
        <div className="flex items-center justify-center min-h-[60vh]">
          <div className="animate-pulse text-muted-foreground">Loading...</div>
        </div>
      </main>
    );
  }

  // Not authenticated
  if (!session) {
    return null; // Will redirect
  }

  return (
    <main id="main-content" className="container mx-auto px-4 py-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <Link
            href="/dashboard"
            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors mb-4"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
          </Link>
          <h1 className="text-3xl font-bold flex items-center gap-3">
            <Sparkles className="w-8 h-8 text-primary" />
            Create Your Plushie
          </h1>
          <p className="text-muted-foreground mt-2">
            Transform your photos into adorable plushie-style images
          </p>
        </div>

        {/* Progress Steps (hidden during processing/result) */}
        {(step === "upload" || step === "configure") && (
          <div className="mb-8">
            <div className="flex items-center justify-center gap-4">
              <StepIndicator
                number={1}
                label="Upload"
                isActive={step === "upload"}
                isComplete={step !== "upload"}
              />
              <div className="w-12 h-px bg-border" />
              <StepIndicator
                number={2}
                label="Configure"
                isActive={step === "configure"}
                isComplete={false}
              />
            </div>
          </div>
        )}

        {/* Main Content */}
        <Card className="border-0 shadow-lg">
          <CardContent className="p-8">
            {step === "upload" && (
              <div className="space-y-6">
                <UploadZone onFileSelect={handleFileSelect} />
                <p className="text-center text-sm text-muted-foreground">
                  For best results, use a clear photo with good lighting
                </p>
              </div>
            )}

            {step === "configure" && selectedFile && previewUrl && (
              <div className="space-y-8">
                <div className="grid md:grid-cols-2 gap-8 items-start">
                  {/* Image Preview */}
                  <ImagePreviewCard
                    file={selectedFile}
                    previewUrl={previewUrl}
                    onRemove={handleRemoveFile}
                    onReplace={handleReplaceFile}
                  />

                  {/* Configuration */}
                  <div className="space-y-6">
                    <SubjectTypeSelector
                      value={subjectType}
                      onChange={setSubjectType}
                    />

                    <div className="flex flex-col items-center gap-4 pt-4">
                      <CreditIndicator creditsAvailable={userCredits} />

                      <Button
                        onClick={handleGenerate}
                        size="lg"
                        className="w-full max-w-xs gap-2"
                        disabled={userCredits < 1}
                      >
                        <Sparkles className="w-4 h-4" />
                        Generate Plushie
                        <ArrowRight className="w-4 h-4" />
                      </Button>

                      {userCredits < 1 && (
                        <Link href="/pricing">
                          <Button variant="outline" size="sm">
                            Get More Credits
                          </Button>
                        </Link>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            )}

            {step === "processing" && (
              <div className="py-8">
                <ProcessingOverlay onComplete={handleProcessingComplete} />
              </div>
            )}

            {step === "result" && previewUrl && (
              <ResultDisplay
                originalUrl={previewUrl}
                plushieUrl={MOCK_PLUSHIE_URL}
                onCreateAnother={handleCreateAnother}
              />
            )}
          </CardContent>
        </Card>
      </div>
    </main>
  );
}

function StepIndicator({
  number,
  label,
  isActive,
  isComplete,
}: {
  number: number;
  label: string;
  isActive: boolean;
  isComplete: boolean;
}) {
  return (
    <div className="flex items-center gap-2">
      <div
        className={`
          w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-colors
          ${
            isActive
              ? "bg-primary text-primary-foreground"
              : isComplete
                ? "bg-primary/20 text-primary"
                : "bg-muted text-muted-foreground"
          }
        `}
      >
        {isComplete ? "✓" : number}
      </div>
      <span
        className={`text-sm font-medium ${
          isActive ? "text-foreground" : "text-muted-foreground"
        }`}
      >
        {label}
      </span>
    </div>
  );
}
